<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <AssemblyName>Mabinogi Overlay</AssemblyName>
    <Title>Mabinogi Overlay</Title>
    <Product>Mabinogi Overlay</Product>
    <Version>0.0.4.3</Version>
    <AssemblyVersion>0.0.4.3</AssemblyVersion>
    <FileVersion>0.0.4.3</FileVersion>
    <InformationalVersion>0.0.4.3</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>..\..\Image\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="4.3.0" />
    <PackageReference Include="Vortice.Direct2D1" Version="3.8.3" />
    <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
    <PackageReference Include="Vortice.DirectComposition" Version="3.8.3" />
    <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Remove="System.Drawing" />
    <Using Remove="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="..\..\Image\Logo.png" Link="Image\Logo.png" />
    <Resource Include="..\..\Image\AppIcon.ico" Link="Image\AppIcon.ico" />
    <Resource Include="..\..\Image\BattlefieldOff.png" Link="Image\BattlefieldOff.png" />
    <Resource Include="..\..\Image\BattlefieldOn.png" Link="Image\BattlefieldOn.png" />
    <Resource Include="..\..\Image\MarchOff.png" Link="Image\MarchOff.png" />
    <Resource Include="..\..\Image\MarchOn.png" Link="Image\MarchOn.png" />
    <Resource Include="..\..\Image\RichyearOff.png" Link="Image\RichyearOff.png" />
    <Resource Include="..\..\Image\RichyearOn.png" Link="Image\RichyearOn.png" />
    <Resource Include="..\..\Image\DivineLinkOff.png" Link="Image\DivineLinkOff.png" />
    <Resource Include="..\..\Image\DivineLinkOn.png" Link="Image\DivineLinkOn.png" />
    <Resource Include="..\..\Image\ConditionSupportOff.png" Link="Image\ConditionSupportOff.png" />
    <Resource Include="..\..\Image\ConditionSupportOn.png" Link="Image\ConditionSupportOn.png" />
    <Resource Include="..\..\Image\PurificationWaveOff.png" Link="Image\PurificationWaveOff.png" />
    <Resource Include="..\..\Image\PurificationWaveOn.png" Link="Image\PurificationWaveOn.png" />
    <Resource Include="..\..\Image\Tuairim.png" Link="Image\Tuairim.png" />
    <Resource Include="..\..\Image\Guide\*.png" Link="Image\Guide\%(Filename)%(Extension)" />
    <Resource Include="..\..\Image\VivaceOff.png" Link="Image\VivaceOff.png" />
    <Resource Include="..\..\Image\VivaceOn.png" Link="Image\VivaceOn.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Localization\*.lang" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
